modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Santi-PdR/AFK---Cinematics/issues"

[[mods]]
modId="afkcinematics"
version="${version}"
displayName="AFK Cinematics"
logoFile="icon.png"
authors="Spunkyinsaan; Forge port by Santi-PdR"
description='''
Starts smooth cinematic camera shots after the client player becomes inactive.
'''

[[dependencies.afkcinematics]]
modId="forge"
mandatory=true
versionRange="[47.4.10,)"
ordering="NONE"
side="CLIENT"

[[dependencies.afkcinematics]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"
